### ISSUE TITLE
"Go Back" button in browser does not go back to previous search queries

### ISSUE THREAD

**Issue by RuoshuiM** [stuyspec/stuyspec.com#165]
Not sure if this issue is already opened.

I think the point of adding "?query=" after URL when searching is to be able to use "go back" or "go forward" in browser to navigate through search histories. But when I tried going back or going forward, I only see the URL changes, and the search result stays the same.

**Comment by NicholasLYang** [comment]
Good catch! I fixed it with some adjustments to how SearchPage works. Basically, we were storing the query in local state, instead of just using a prop. This meant that when the query changed, the component wasn't notified, and wouldn't update. I changed it so that we just use the query directly from props (nice feature by React Router is that they pass down the location to child components of Route). 

If you want me to walk you through the solution in more detail, I can. In the meanwhile, keep reporting bugs like this!

**Comment by RuoshuiM** [comment]
I'm not sure if I'm sending this to Nicholas Yang, my intended recipient,
please reply if you are.

When should I see the changes reflected in the actual website? (
www.stuyspec.com
<http://mailstat.us/tr/t/771nh4xajlvm5nfz/2/http://www.stuyspec.com/>) (I'm
asking since I'm still not seeing the "Go Back" on search page problem
fixed on www.stuyspec.com
<http://mailstat.us/tr/t/771nh4xajlvm5nfz/4/http://www.stuyspec.com/>)
How often is the website deployed with the newest code from the codebase?

<http://mailstat.us/tr/opt-out?guid=771nh4xajlvm5nfz>

**Comment by NicholasLYang** [comment]
Oops, yeah I only pushed it to staging. I'll push it to production now.
Fair warning, it may not show up immediately cause of our CDN.

**Comment by RuoshuiM** [comment]
Now I see the change.
The search result updated, but the search field stayed the same. (I'm guessing: is the SearchForm not notified? Would a lifecycle method solve the problem?)

Also, the preview of the search results seems to be escaped, thus a "<i></i>" tag shows up as text.
![image](https://user-images.githubusercontent.com/19398896/45395173-de442d80-b602-11e8-8d5a-155b18d71113.png)
Would this be an easy fix?
